using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using u_api.Modelos;

namespace u_api.Repositories
{
    public class RPUniversidades
    {
        public static List<Universidad> _listUniversidades = new List<Universidad>()
        {
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL MAYOR DE SAN MARCOS", departamento = "Lima", provincia = "Lima", distrito = "Lima" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL DE SAN CRISTÓBAL DE HUAMANGA", departamento = "Ayacucho", provincia = "Huamanga", distrito = "Ayacucho" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL DE TRUJILLO", departamento = "La Libertad", provincia = "Trujillo", distrito = "Trujillo" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL DE SAN AGUSTÍN DE AREQUIPA", departamento = "Arequipa", provincia = "Arequipa", distrito = "Arequipa" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL DE INGENIERÍA", departamento = "Lima", provincia = "Lima", distrito = "Rímac" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL AGRARIA LA MOLINA", departamento = "Lima", provincia = "Lima", distrito = "La Molina" },
            new Universidad() { nombre = "PONTIFICIA UNIVERSIDAD CATÓLICA DEL PERÚ", departamento = "Lima", provincia = "Lima", distrito = "San Miguel" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL DE LA AMAZONÍA PERUANA", departamento = "Loreto", provincia = "Maynas", distrito = "San Juan Bautista" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL DEL ALTIPLANO", departamento = "Puno", provincia = "Puno", distrito = "Puno" },
            new Universidad() { nombre = "UNIVERSIDAD PERUANA CAYETANO HEREDIA", departamento = "Lima", provincia = "Lima", distrito = "San Martín De Porres" },
            new Universidad() { nombre = "UNIVERSIDAD CATÓLICA DE SANTA MARÍA", departamento = "Arequipa", provincia = "Arequipa", distrito = "Arequipa" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL DE CAJAMARCA", departamento = "Cajamarca", provincia = "Cajamarca", distrito = "Cajamarca" },
            new Universidad() { nombre = "UNIVERSIDAD DEL PACÍFICO", departamento = "Lima", provincia = "Lima", distrito = "Jesús María" },
            new Universidad() { nombre = "UNIVERSIDAD DE LIMA", departamento = "Lima", provincia = "Lima", distrito = "Santiago De Surco" },
            new Universidad() { nombre = "UNIVERSIDAD DE SAN MARTÍN DE PORRES", departamento = "Lima", provincia = "Lima", distrito = "Santa Anita" },
            new Universidad() { nombre = "UNIVERSIDAD FEMENINA DEL SAGRADO CORAZÓN", departamento = "Lima", provincia = "Lima", distrito = "La Molina" },
            new Universidad() { nombre = "UNIVERSIDAD DE PIURA", departamento = "Piura", provincia = "Piura", distrito = "Piura" },
            new Universidad() { nombre = "UNIVERSIDAD RICARDO PALMA", departamento = "Lima", provincia = "Lima", distrito = "Santiago De Surco" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL JORGE BASADRE GROHMANN", departamento = "Tacna", provincia = "Tacna", distrito = "Tacna" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL SANTIAGO ANTÚNEZ DE MAYOLO", departamento = "Áncash", provincia = "Huaraz", distrito = "Independencia" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL DE UCAYALI", departamento = "Ucayali", provincia = "Coronel Portillo", distrito = "Calleria" },
            new Universidad() { nombre = "UNIVERSIDAD PERUANA UNIÓN", departamento = "Lima", provincia = "Lima", distrito = "Lurigancho" },
            new Universidad() { nombre = "UNIVERSIDAD ANDINA DEL CUSCO", departamento = "Cusco", provincia = "Cusco", distrito = "San Jerónimo" },
            new Universidad() { nombre = "UNIVERSIDAD PRIVADA DE TACNA", departamento = "Tacna", provincia = "Tacna", distrito = "Pocollay" },
            new Universidad() { nombre = "UNIVERSIDAD PRIVADA ANTENOR ORREGO", departamento = "La Libertad", provincia = "Trujillo", distrito = "Trujillo" },
            new Universidad() { nombre = "UNIVERSIDAD MARCELINO CHAMPAGNAT", departamento = "Lima", provincia = "Lima", distrito = "Santiago De Surco" },
            new Universidad() { nombre = "UNIVERSIDAD PERUANA DE CIENCIAS APLICADAS S.A.C.", departamento = "Lima", provincia = "Lima", distrito = "Santiago De Surco" },
            new Universidad() { nombre = "UNIVERSIDAD PRIVADA DEL NORTE S.A.C.", departamento = "La Libertad", provincia = "Trujillo", distrito = "Trujillo" },
            new Universidad() { nombre = "UNIVERSIDAD SAN IGNACIO DE LOYOLA S.A.", departamento = "Lima", provincia = "Lima", distrito = "La Molina" },
            new Universidad() { nombre = "UNIVERSIDAD CATÓLICA SAN PABLO", departamento = "Arequipa", provincia = "Arequipa", distrito = "Arequipa" },
            new Universidad() { nombre = "UNIVERSIDAD CIENTÍFICA DEL SUR S.A.C.", departamento = "Lima", provincia = "Lima", distrito = "Villa El Salvador" },
            new Universidad() { nombre = "UNIVERSIDAD CATÓLICA SANTO TORIBIO DE MOGROVEJO", departamento = "Lambayeque", provincia = "Chiclayo", distrito = "Chiclayo" },
            new Universidad() { nombre = "UNIVERSIDAD CATÓLICA SEDES SAPIENTIAE", departamento = "Lima", provincia = "Lima", distrito = "Los Olivos" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL TORIBIO RODRÍGUEZ DE MENDOZA DE AMAZONAS", departamento = "Amazonas", provincia = "Chachapoyas", distrito = "Chachapoyas" },
            new Universidad() { nombre = "UNIVERSIDAD ESAN", departamento = "Lima", provincia = "Lima", distrito = "Santiago De Surco" },
            new Universidad() { nombre = "UNIVERSIDAD ANTONIO RUIZ DE MONTOYA", departamento = "Lima", provincia = "Lima", distrito = "Pueblo Libre" },
            new Universidad() { nombre = "UNIVERSIDAD PARA EL DESARROLLO ANDINO", departamento = "Huancavelica", provincia = "Angaraes", distrito = "Lircay" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL INTERCULTURAL DE LA AMAZONÍA", departamento = "Ucayali", provincia = "Coronel Portillo", distrito = "Yarinacocha" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL JOSÉ MARÍA ARGUEDAS", departamento = "Apurímac", provincia = "Andahuaylas", distrito = "San Jerónimo" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL DE MOQUEGUA", departamento = "Moquegua", provincia = "Mariscal Nieto", distrito = "Moquegua" },
            new Universidad() { nombre = "UNIVERSIDAD AUTÓNOMA DEL PERÚ S.A.C.", departamento = "Lima", provincia = "Lima", distrito = "Villa El Salvador" },
            new Universidad() { nombre = "ASOCIACIÓN CIVIL UNIVERSIDAD DE CIENCIAS Y HUMANIDADES", departamento = "Lima", provincia = "Lima", distrito = "Los Olivos" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL DE JULIACA", departamento = "Puno", provincia = "San Román", distrito = "Juliaca" },
            new Universidad() { nombre = "UNIVERSIDAD JAIME BAUSATE Y MEZA", departamento = "Lima", provincia = "Lima", distrito = "Jesús María" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL DE JAÉN", departamento = "Cajamarca", provincia = "Jaén", distrito = "Jaén" },
            new Universidad() { nombre = "UNIVERSIDAD LE CORDON BLEU S.A.C.", departamento = "Lima", provincia = "Lima", distrito = "Magdalena Del Mar" },
            new Universidad() { nombre = "UNIVERSIDAD DE CIENCIAS Y ARTES DE AMÉRICA LATINA S.A.C.", departamento = "Lima", provincia = "Lima", distrito = "La Molina" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL AUTÓNOMA DE CHOTA", departamento = "Cajamarca", provincia = "Chota", distrito = "Chota" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL DE BARRANCA", departamento = "Lima", provincia = "Barranca", distrito = "Barranca" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL DE CAÑETE", departamento = "Lima", provincia = "Cañete", distrito = "San Vicente De Cañete" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL INTERCULTURAL FABIOLA SALAZAR LEGUÍA DE BAGUA", departamento = "Amazonas", provincia = "Bagua", distrito = "Bagua" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL INTERCULTURAL DE LA SELVA CENTRAL JUAN SANTOS ATAHUALPA", departamento = "Junín", provincia = "Chanchamayo", distrito = "Chanchamayo" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL AUTÓNOMA DE ALTO AMAZONAS", departamento = "Loreto", provincia = "Alto Amazonas", distrito = "Yurimaguas" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL AUTÓNOMA ALTOANDINA DE TARMA", departamento = "Junín", provincia = "Tarma", distrito = "Tarma" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL AUTÓNOMA DE HUANTA", departamento = "Ayacucho", provincia = "Huanta", distrito = "Huanta" },
            new Universidad() { nombre = "UNIVERSIDAD DE INGENIERÍA Y TECNOLOGÍA", departamento = "Lima", provincia = "Lima", distrito = "Barranco" },
            new Universidad() { nombre = "UNIVERSIDAD LA SALLE", departamento = "Arequipa", provincia = "Arequipa", distrito = "Arequipa" },
            new Universidad() { nombre = "UNIVERSIDAD MARÍA AUXILIADORA S.A.C.", departamento = "Lima", provincia = "Lima", distrito = "San Juan De Lurigancho" },
            new Universidad() { nombre = "UNIVERSIDAD CONTINENTAL S.A.C.", departamento = "Junín", provincia = "Huancayo", distrito = "Huancayo" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL TECNOLÓGICA DE LIMA SUR", departamento = "Lima", provincia = "Lima", distrito = "Villa El Salvador" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL TECNOLÓGICA DE SAN JUAN DE LURIGANCHO", departamento = "Lima", provincia = "Lima", distrito = "San Juan De Lurigancho" },
            new Universidad() { nombre = "UNIVERSIDAD AUTÓNOMA MUNICIPAL DE LOS OLIVOS", departamento = "Lima", provincia = "Lima", distrito = "Los Olivos" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL AUTÓNOMA DE TAYACAJA DANIEL HERNÁNDEZ MORILLO", departamento = "Huancavelica", provincia = "Tayacaja", distrito = "Daniel Hernández" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL CIRO ALEGRÍA", departamento = "La Libertad", provincia = "Sánchez Carrión", distrito = "Huamachuco" },
            new Universidad() { nombre = "UNIVERSIDAD SEMINARIO EVANGÉLICO DE LIMA", departamento = "Lima", provincia = "Lima", distrito = "La Molina" },
            new Universidad() { nombre = "UNIVERSIDAD SEMINARIO BÍBLICO ANDINO", departamento = "Lima", provincia = "Lima", distrito = "Pueblo Libre" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL DE SAN ANTONIO ABAD DEL CUSCO", departamento = "Cusco", provincia = "Cusco", distrito = "Cusco" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL SAN LUIS GONZAGA DE ICA", departamento = "Ica", provincia = "Ica", distrito = "Ica" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL DEL CENTRO DEL PERÚ", departamento = "Junín", provincia = "Huancayo", distrito = "El Tambo" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL DE PIURA", departamento = "Piura", provincia = "Piura", distrito = "Castilla" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL FEDERICO VILLARREAL", departamento = "Lima", provincia = "Lima", distrito = "Lima" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL AGRARIA DE LA SELVA", departamento = "Huánuco", provincia = "Leoncio Prado", distrito = "Rupa-Rupa" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL HERMILIO VALDIZÁN DE HUÁNUCO", departamento = "Huánuco", provincia = "Huánuco", distrito = "Pillco Marca" },
            new Universidad() { nombre = "UNIVERSIDAD INCA GARCILASO DE LA VEGA ASOCIACIÓN CIVIL", departamento = "Lima", provincia = "Lima", distrito = "Lince" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL DE EDUCACIÓN ENRIQUE GUZMÁN Y VALLE", departamento = "Lima", provincia = "Lima", distrito = "Lurigancho" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL DANIEL ALCIDES CARRIÓN", departamento = "Pasco", provincia = "Pasco", distrito = "Yanacancha" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL DEL CALLAO", departamento = "Callao", provincia = "Prov. Const. Del Callao", distrito = "Bellavista" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL JOSÉ FAUSTINO SÁNCHEZ CARRIÓN", departamento = "Lima", provincia = "Huaura", distrito = "Huacho" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL PEDRO RUIZ GALLO", departamento = "Lambayeque", provincia = "Lambayeque", distrito = "Lambayeque" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL DE SAN MARTÍN", departamento = "San Martín", provincia = "San Martín", distrito = "Tarapoto" },
            new Universidad() { nombre = "UNIVERSIDAD ANDINA NÉSTOR CÁCERES VELÁSQUEZ", departamento = "Puno", provincia = "San Román", distrito = "Juliaca" },
            new Universidad() { nombre = "UNIVERSIDAD PERUANA LOS ANDES", departamento = "Junín", provincia = "Huancayo", distrito = "Huancayo" },
            new Universidad() { nombre = "UNIVERSIDAD TECNOLÓGICA DE LOS ANDES", departamento = "Apurímac", provincia = "Abancay", distrito = "Abancay" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL DE TUMBES", departamento = "Tumbes", provincia = "Tumbes", distrito = "Tumbes" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL DEL SANTA", departamento = "Áncash", provincia = "Santa", distrito = "Nuevo Chimbote" },
            new Universidad() { nombre = "UNIVERSIDAD PARTICULAR DE CHICLAYO", departamento = "Lambayeque", provincia = "Chiclayo", distrito = "Pimentel" },
            new Universidad() { nombre = "UNIVERSIDAD DE HUÁNUCO", departamento = "Huánuco", provincia = "Huánuco", distrito = "Huanuco" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL DE HUANCAVELICA", departamento = "Huancavelica", provincia = "Huancavelica", distrito = "Huancavelica" },
            new Universidad() { nombre = "UNIVERSIDAD CÉSAR VALLEJO S.A.C.", departamento = "La Libertad", provincia = "Trujillo", distrito = "Victor Larco Herrera" },
            new Universidad() { nombre = "UNIVERSIDAD ALAS PERUANAS S.A.", departamento = "Lima", provincia = "Lima", distrito = "Jesús María" },
            new Universidad() { nombre = "UNIVERSIDAD PRIVADA NORBERT WIENER S.A.", departamento = "Lima", provincia = "Lima", distrito = "Lima" },
            new Universidad() { nombre = "UNIVERSIDAD TECNOLÓGICA DEL PERÚ S.A.C.", departamento = "Lima", provincia = "Lima", distrito = "Lima" },
            new Universidad() { nombre = "UNIVERSIDAD PRIVADA ANTONIO GUILLERMO URRELO S.A.C.", departamento = "Cajamarca", provincia = "Cajamarca", distrito = "Cajamarca" },
            new Universidad() { nombre = "UNIVERSIDAD SEÑOR DE SIPÁN S.A.C.", departamento = "Lambayeque", provincia = "Chiclayo", distrito = "Pimentel" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL AMAZÓNICA DE MADRE DE DIOS", departamento = "Madre De Dios", provincia = "Tambopata", distrito = "Tambopata" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL MICAELA BASTIDAS DE APURÍMAC", departamento = "Apurímac", provincia = "Abancay", distrito = "Tamburco" },
            new Universidad() { nombre = "UNIVERSIDAD PERUANA DE LAS AMÉRICAS S.A.C.", departamento = "Lima", provincia = "Lima", distrito = "Lima" },
            new Universidad() { nombre = "UNIVERSIDAD PERUANA DE CIENCIAS E INFORMÁTICA S.A.C.", departamento = "Lima", provincia = "Lima", distrito = "Lince" },
            new Universidad() { nombre = "UNIVERSIDAD PRIVADA TELESUP S.A.C.", departamento = "Lima", provincia = "Lima", distrito = "Lima" },
            new Universidad() { nombre = "UNIVERSIDAD SAN PEDRO", departamento = "Áncash", provincia = "Santa", distrito = "Chimbote" },
            new Universidad() { nombre = "UNIVERSIDAD JOSÉ CARLOS MARIÁTEGUI", departamento = "Moquegua", provincia = "Mariscal Nieto", distrito = "Moquegua" },
            new Universidad() { nombre = "UNIVERSIDAD CIENTÍFICA DEL PERÚ", departamento = "Loreto", provincia = "Maynas", distrito = "San Juan Bautista" },
            new Universidad() { nombre = "UNIVERSIDAD CATÓLICA LOS ÁNGELES DE CHIMBOTE", departamento = "Áncash", provincia = "Santa", distrito = "Chimbote" },
            new Universidad() { nombre = "UNIVERSIDAD PRIVADA SAN JUAN BAUTISTA S.A.C.", departamento = "Lima", provincia = "Lima", distrito = "Chorrillos" },
            new Universidad() { nombre = "UNIVERSIDAD CATÓLICA DE TRUJILLO BENEDICTO XVI", departamento = "La Libertad", provincia = "Trujillo", distrito = "Moche" },
            new Universidad() { nombre = "UNIVERSIDAD PRIVADA SERGIO BERNALES S.A.", departamento = "Lima", provincia = "Cañete", distrito = "San Vicente De Cañete" },
            new Universidad() { nombre = "UNIVERSIDAD PRIVADA DE PUCALLPA S.A.C.", departamento = "Ucayali", provincia = "Coronel Portillo", distrito = "Calleria" },
            new Universidad() { nombre = "UNIVERSIDAD PRIVADA DE TRUJILLO", departamento = "La Libertad", provincia = "Trujillo", distrito = "Laredo" },
            new Universidad() { nombre = "UNIVERSIDAD PRIVADA SAN CARLOS S.A.C.", departamento = "Puno", provincia = "Puno", distrito = "Puno" },
            new Universidad() { nombre = "UNIVERSIDAD PERUANA SIMÓN BOLÍVAR S.A.C.", departamento = "Lima", provincia = "Lima", distrito = "Pueblo Libre" },
            new Universidad() { nombre = "UNIVERSIDAD PERUANA DEL ORIENTE S.A.C.", departamento = "Loreto", provincia = "Maynas", distrito = "San Juan Bautista" },
            new Universidad() { nombre = "UNIVERSIDAD PRIVADA JUAN MEJÍA BACA S.A.C.", departamento = "Lambayeque", provincia = "Chiclayo", distrito = "Chiclayo" },
            new Universidad() { nombre = "UNIVERSIDAD PERUANA DEL CENTRO", departamento = "Junín", provincia = "Huancayo", distrito = "Huancayo" },
            new Universidad() { nombre = "UNIVERSIDAD PRIVADA ARZOBISPO LOAYZA S.A.C.", departamento = "Lima", provincia = "Lima", distrito = "Lima" },
            new Universidad() { nombre = "UNIVERSIDAD PRIVADA DE HUANCAYO FRANKLIN ROOSEVELT S.A.C.", departamento = "Junín", provincia = "Huancayo", distrito = "Huancayo" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL DE FRONTERA", departamento = "Piura", provincia = "Sullana", distrito = "Sullana" },
            new Universidad() { nombre = "UNIVERSIDAD CIENCIAS DE LA SALUD S.A.C.", departamento = "Arequipa", provincia = "Arequipa", distrito = "Yanahuara" },
            new Universidad() { nombre = "UNIVERSIDAD DE AYACUCHO FEDERICO FROEBEL S.A.C.", departamento = "Ayacucho", provincia = "Huamanga", distrito = "Ayacucho" },
            new Universidad() { nombre = "UNIVERSIDAD PERUANA AUSTRAL DEL CUSCO S.A.C.", departamento = "Cusco", provincia = "Cusco", distrito = "Cusco" },
            new Universidad() { nombre = "UNIVERSIDAD AUTÓNOMA SAN FRANCISCO S.A.C.", departamento = "Arequipa", provincia = "Arequipa", distrito = "Tiabaya" },
            new Universidad() { nombre = "UNIVERSIDAD SAN ANDRÉS S.A.C.", departamento = "Lima", provincia = "Lima", distrito = "Independencia" },
            new Universidad() { nombre = "UNIVERSIDAD INTERAMERICANA PARA EL DESARROLLO S.A.C.", departamento = "Lima", provincia = "Lima", distrito = "Breña" },
            new Universidad() { nombre = "UNIVERSIDAD PRIVADA JUAN PABLO II S.A.C.", departamento = "Lima", provincia = "Lima", distrito = "Ate" },
            new Universidad() { nombre = "UNIVERSIDAD PRIVADA LEONARDO DA VINCI S.A.C.", departamento = "La Libertad", provincia = "Trujillo", distrito = "Trujillo" },
            new Universidad() { nombre = "UNIVERSIDAD NACIONAL INTERCULTURAL DE QUILLABAMBA", departamento = "Cusco", provincia = "La Convención", distrito = "Santa Ana" },
            new Universidad() { nombre = "UNIVERSIDAD LATINOAMERICANA CIMA S.A.C.", departamento = "Tacna", provincia = "Tacna", distrito = "Tacna" },
            new Universidad() { nombre = "UNIVERSIDAD PRIVADA AUTÓNOMA DEL SUR S.A.C.", departamento = "Arequipa", provincia = "Arequipa", distrito = "Arequipa" },
            new Universidad() { nombre = "UNIVERSIDAD SANTO DOMINGO DE GUZMÁN S.A.C.", departamento = "Lima", provincia = "Huarochirí", distrito = "San Antonio" },
            new Universidad() { nombre = "UNIVERSIDAD PRIVADA LÍDER PERUANA S.A.C.", departamento = "Cusco", provincia = "La Convención", distrito = "Santa Ana" },
            new Universidad() { nombre = "UNIVERSIDAD PRIVADA PERUANO ALEMANA S.A.C.", departamento = "Lima", provincia = "Lima", distrito = "Chorrillos" },
            new Universidad() { nombre = "UNIVERSIDAD GLOBAL DEL CUSCO S.A.C.", departamento = "Cusco", provincia = "Cusco", distrito = "Cusco" },
            new Universidad() { nombre = "UNIVERSIDAD PERUANA SANTO TOMÁS DE AQUINO DE CIENCIA E INTEGRACIÓN S.A.C.", departamento = "Junín", provincia = "Huancayo", distrito = "Huancayo" },
            new Universidad() { nombre = "UNIVERSIDAD PRIVADA SISE S.A.C.", departamento = "Lima", provincia = "Lima", distrito = "Ate" },
            new Universidad() { nombre = "GRUPO EDUCATIVO UNIVERSIDAD PRIVADA DE ICA S.A.C.", departamento = "Ica", provincia = "Ica", distrito = "Ica" },
            new Universidad() { nombre = "UNIVERSIDAD AUTÓNOMA DE ICA S.A.C.", departamento = "Ica", provincia = "Chincha", distrito = "Chincha Alta" },
            new Universidad() { nombre = "UNIVERSIDAD PRIVADA DE LA SELVA PERUANA S.A.C.", departamento = "Loreto", provincia = "Maynas", distrito = "Iquitos" },
            new Universidad() { nombre = "UNIVERSIDAD POLITÉCNICA AMAZÓNICA S.A.C.", departamento = "Amazonas", provincia = "Utcubamba", distrito = "Bagua Grande" },
            new Universidad() { nombre = "UNIVERSIDAD PERUANA DE INTEGRACIÓN GLOBAL S.A.C.", departamento = "Lima", provincia = "Lima", distrito = "Santiago De Surco" },
            new Universidad() { nombre = "UNIVERSIDAD DE LAMBAYEQUE S.A.C.", departamento = "Lambayeque", provincia = "Chiclayo", distrito = "Chiclayo" },
            new Universidad() { nombre = "UNIVERSIDAD PERUANA DE ARTE ORVAL S.A.C.", departamento = "Lima", provincia = "Lima", distrito = "San Borja" },
            new Universidad() { nombre = "UNIVERSIDAD PERUANA DE INVESTIGACIÓN Y NEGOCIOS S.A.C.", departamento = "Lima", provincia = "Lima", distrito = "Jesús María" },
            new Universidad() { nombre = "UNIVERSIDAD MARÍTIMA DEL PERÚ S.A.C.", departamento = "Callao", provincia = "Prov. Const. Del Callao", distrito = "Callao" },
            new Universidad() { nombre = "FACULTAD DE TEOLOGÍA PONTIFICIA Y CIVIL DE LIMA", departamento = "Lima", provincia = "Lima", distrito = "Pueblo Libre" }


        };
        public IEnumerable<Universidad> getUniversidades()
        {
            return _listUniversidades;
        }public Universidad getUniversidad(string nombre)
        {
            var uni = _listUniversidades.Where(un => un.nombre == nombre);
            return uni.FirstOrDefault();
        }
        public void addUniversidad(Universidad uni) {
            _listUniversidades.Add(uni);
        }

    }
}
